site_name: 天涯神贴大合集
site_url: https://tianya.zhihu.blog/
site_author: shutouyabo
site_description: >-
  wiki tianya

repo_name: 天涯神贴
repo_url: https://github.com/shutouyabo/tianyashentie/

copyright: Copyright &copy; 2026 <a href="https://tianya.zhihu.blog/" target="_blank" rel="noopener noreferrer">天涯神贴</a>



theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true

  - search:
      lang:
        - zh
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://v6.51.la/land/L0ZDlWY6HhH0NxKi
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: "index.md"
  - 1 - 天涯神贴210:
      - "天涯神贴210（1-50篇）": "c1/c1_01.md"
      - "天涯神贴210（51-100篇）": "c1/c1_02.md"
      - "天涯神贴210（101-150篇）": "c1/c1_03.md"
      - "天涯神贴210（151-194篇）": "c1/c1_04.md"
  - 2 - 蓬莱鬼话、玄幻灵异、中医命理:
      - "蓬莱鬼话、玄幻灵异、中医命理 1-37篇": "c2/c2_01.md"
  - 3 - 金融财经、股市楼市、经济预测:
      - "金融财经、股市楼市、经济预测 1-50篇": "c3/c3_01.md"
      - "金融财经、股市楼市、经济预测 51-100篇": "c3/c3_02.md"
      - "金融财经、股市楼市、经济预测 101-127篇": "c3/c3_03.md"
  - 4 - 人在江湖、古今热点、成长箴言:
      - "人在江湖、古今热点、成长箴言 1-35篇": "c4/c4_01.md"
      - "人在江湖、古今热点、成长箴言 36-70篇": "c4/c4_02.md"
  - 5 - 天涯高阶神贴:
      - "天涯高阶神贴1-50篇": "c5/c5_01.md"
      - "天涯高阶神贴51-100篇": "c5/c5_02.md"
      - "天涯高阶神贴101-150篇": "c5/c5_03.md"
      - "天涯高阶神贴151-190篇": "c5/c5_04.md"
  - 6 - 十一大板块:
      - "KK大神": "c6/c6_01.md"
      - "懒兔子": "c6/c6_02.md"
      - "九哥合集": "c6/c6_03.md"
      - "蓬莲鬼话": "c6/c6_04.md"
      - "禅海商道": "c6/c6_05.md"
      - "股市楼市": "c6/c6_06.md"
      - "缠中说禅": "c6/c6_07.md"
      - "创业家园": "c6/c6_08.md"
      - "经济论坛": "c6/c6_09.md"
      - "国际观察": "c6/c6_10.md"
      - "盛京剑客": "c6/c6_11.md"
      - "地缘看世界": "c6/c6_12.md"
      - "大家常读的贴": "c6/c6_13.md"
      - "开窍开悟开智5册": "c6/c6_14.md"
      - "独家稀有贴整理新增": "c6/c6_15.md"



